<?php

/**
 * @file
 * rest_consumer module hooks.
 */

/**
 * Implements hook_theme()
 */
function rest_consumer_theme($existing, $type, $theme, $path) {
  return [
    'rest_consumer_page' => [
      'template' => 'recent-posts',
      'path' => $path . '/templates',
      'variables' => [
        'posts' => [],
      ],
      
    ],
    'rest_consumer_post' => [
      'template' => 'post',
      'path' => $path . '/templates',
      'variables' => [ 
        'id' => NULL,
        'date' => NULL,
        'title' => NULL,
        'url' => NULL,  
      ],
    ],
    'views_view__rest_consumer_posts' => [
      'template' => 'views-view--rest-consumer-posts',
      'base hook' => 'view',
    ],
    'views_view_unformatted__rest_consumer_posts' => [
      'template' => 'views-view-unformatted--rest-consumer-posts',
      'base hook' => 'view',
    ],
    'views_view_fields__rest_consumer_posts' => [
      'template' => 'views-view-fields--rest-consumer-posts',
      'base hook' => 'view_fields',
    ]
  ];
}